# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  healthbuddyserver:
    image: healthbuddyserver
    build:
      context: .
      dockerfile: HealthBuddy.Server/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5289:5289
      - 7222:7222
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
